name: all steps

on:
  workflow_dispatch

jobs:
  job_1:
    runs-on: ubuntu-latest

    steps: 
      - run: |
          npm install
          npm rub build
        working-directory: ./temp
        shell: bash

      - run: print %ENV
        
