name: External Trigger Test

on: 
  repository_dispatch:
    types: [deploy_app]

jobs:
    test_job:
      runs-on: ubuntu-latest
      steps:
        - name: Print event payload
          run: echo "Received event"
