name: multiple jobs

on:
  workflow_dispatch:

jobs:

  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: print job_1 on screen
        run: echo "job ${{github.job}}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: print job_2 on screen
        run: echo "job ${{github.job}}"

  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: print job_3 on screen
        run: echo "job ${{github.job}}"

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2,job_3]
    steps:
      - name: print job_4 on screen
        run: echo "job ${{github.job}}"

        
