on:
  workflow_call:
    inputs:
      ENV:
        type: string
        default: "development"
      value:
        type: number
        default: 10


jobs:
    TEST_JOB:
        runs-on: ubuntu-latest

        steps:
            - name: print environment
              run: echo "environment is ${{ inputs.ENV }} - value ${{ inputs.value }}"