name: Test Run Schedule Trigger

on:
    schedule:
        - cron: "25 * * * *"

jobs:
    daily_task:
        runs-on: ubuntu-latest

        steps:
            - name: Print Message
              run: echo "running Schedule Tasks"

