name: Caller Workflow

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment name'
        type: string
        required: true
        default: 'production'
      value:
        description: 'A numeric value'
        type: number
        required: true
        default: 50

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      ENV: ${{ github.event.inputs.ENV }}
      value: ${{ github.event.inputs.value }}
