name: ahla msa 3la yasser

on: 
  push:
    branches:
      - master



jobs:
    yasser-job:
        runs-on: ubuntu-latest
    
        steps:
            - name: install python and flask
              run: sudo apt install python3 && pip install flask 

            - name: what is version
              run : python3 --version
            
            - name: list files before checkout
              run: ls -lha

            - name: checkout repository
              uses: actions/checkout@v6.0.1
              
            - name: list files after checkout
              run: ls -lha

            - name: test application 
              run: python3 script.py